apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-29-tenant/load-app-ce974521-6a79-41ae-9128-95a1577fc748/devfile-sample-code-with-quarkus@sha256:e9f82bfc5a5c6e8c1f81f6f3631bc4ae2256c4d7283577a7efd241249c658d69
        name: my-java-quarkus
        resources: {}
status: {}
